# Generated by Django 4.2.27 on 2025-12-17 03:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead_extractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Compra'), ('usage', 'Uso'), ('refund', 'Reembolso')], max_length=20)),
                ('amount', models.IntegerField()),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('quantity_requested', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('results_count', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('search_data', models.JSONField(default=dict)),
                ('results_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lead',
            name='cpf_owner',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_extracted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_seen_by_user',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='lead_extractor.userprofile'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='lead_extractor.userprofile'),
        ),
        migrations.AddField(
            model_name='lead',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='lead_extractor.search'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lead_extractor.userprofile'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'cnpj'], name='lead_extrac_user_id_bdce88_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'created_at'], name='lead_extrac_user_id_73d5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['cnpj'], name='lead_extrac_cnpj_911578_idx'),
        ),
    ]
