# Generated by Django 4.2.27 on 2025-12-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_extractor', '0002_credittransaction_search_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViperRequestQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('partners', 'Sócios/QSA')], max_length=20)),
                ('request_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Completo'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viper_requests', to='lead_extractor.userprofile')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='lead_extrac_status_d1104b_idx'), models.Index(fields=['user', 'status'], name='lead_extrac_user_id_95d9a5_idx')],
            },
        ),
    ]
