# Generated by Django 4.2.27 on 2025-12-19 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_extractor', '0004_viperrequestqueue_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedNiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['state', 'city'],
                'indexes': [models.Index(fields=['city', 'state'], name='lead_extrac_city_a63402_idx')],
                'unique_together': {('city', 'state')},
            },
        ),
        migrations.CreateModel(
            name='CachedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche_normalized', models.CharField(max_length=255)),
                ('location_normalized', models.CharField(max_length=255)),
                ('total_leads_cached', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['niche_normalized', 'location_normalized'], name='lead_extrac_niche_n_deadec_idx'), models.Index(fields=['expires_at'], name='lead_extrac_expires_10744b_idx')],
                'unique_together': {('niche_normalized', 'location_normalized')},
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='cached_search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_leads', to='lead_extractor.cachedsearch'),
        ),
        migrations.AddField(
            model_name='search',
            name='cached_search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_searches', to='lead_extractor.cachedsearch'),
        ),
    ]
