# Generated by Django 4.2.27 on 2026-01-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_extractor', '0005_normalizedniche_normalizedlocation_cachedsearch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='status',
            field=models.CharField(choices=[('processing', 'Processando'), ('completed', 'Completo'), ('failed', 'Falhou')], default='completed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['user', 'status', 'created_at'], name='lead_extrac_user_id_f980f1_idx'),
        ),
    ]
