# Generated by Django 4.2.27 on 2026-01-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_extractor', '0006_search_processing_started_at_search_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_seen_by_user',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='normalizedlocation',
            name='city',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='normalizedlocation',
            name='display_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='normalizedlocation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='normalizedlocation',
            name='state',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='normalizedniche',
            name='display_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='normalizedniche',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='normalizedniche',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='supabase_user_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['cached_search', 'cnpj'], name='lead_extrac_cached__85a98e_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedlocation',
            index=models.Index(fields=['display_name', 'is_active'], name='lead_extrac_display_2bd9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedniche',
            index=models.Index(fields=['display_name', 'is_active'], name='lead_extrac_display_d27692_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['supabase_user_id'], name='lead_extrac_supabas_a5cc4b_idx'),
        ),
    ]
