# Generated by Django 4.2.27 on 2026-01-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_extractor', '0007_alter_lead_cnpj_alter_lead_last_seen_by_user_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='viperrequestqueue',
            index=models.Index(fields=['user', 'request_type', 'status'], name='lead_extrac_user_id_66b59e_idx'),
        ),
    ]
