# Generated by Django 4.2.27 on 2026-01-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_extractor', '0008_viperrequestqueue_lead_extrac_user_id_66b59e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_paid', models.IntegerField(default=1)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='cachedsearch',
            name='lead_extrac_expires_10744b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_extrac_user_id_bdce88_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_extrac_user_id_73d5a8_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_seen_by_user',
        ),
        migrations.AlterField(
            model_name='cachedsearch',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='search',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Usar LeadAccess.search. Mantido para migração.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_leads', to='lead_extractor.search'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Usar LeadAccess. Mantido para migração.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_leads', to='lead_extractor.userprofile'),
        ),
        migrations.AddField(
            model_name='leadaccess',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='lead_extractor.lead'),
        ),
        migrations.AddField(
            model_name='leadaccess',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_accesses', to='lead_extractor.search'),
        ),
        migrations.AddField(
            model_name='leadaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_accesses', to='lead_extractor.userprofile'),
        ),
        migrations.AddIndex(
            model_name='leadaccess',
            index=models.Index(fields=['user', 'accessed_at'], name='lead_extrac_user_id_48d463_idx'),
        ),
        migrations.AddIndex(
            model_name='leadaccess',
            index=models.Index(fields=['lead', 'user'], name='lead_extrac_lead_id_e13ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='leadaccess',
            index=models.Index(fields=['search', 'user'], name='lead_extrac_search__2a6461_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadaccess',
            unique_together={('user', 'lead')},
        ),
    ]
